spring.datasource.username=csedatabase_4540_user
spring.datasource.password=ITJ7n8HefpUfJoOWRWB6VUagKsN5zYxQ
spring.datasource.url=jdbc:postgresql:/postgresql://dpg-d6l620lactks73bssm80-a.oregon-postgres.render.com/csedatabase_4540

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${PORT:8080}